### ISSUE TITLE
Configuration of org-recipes

### ISSUE THREAD

**Issue by diego-vicente** [tuhdo/org-recipes#3]
The package idea is brilliant, just what I was looking for! However, I am not sure on the configuration needed. I have up and running org-wiki, and the location is properly set; but I am unable to make org-recipes find any of my files. Is there a previous configuration or kind of setup needed?

**Comment by tuhdo** [comment]
Are you using `use-package`? If so, `org-wiki` must be loaded before it can use the function that returns the file list from `org-wiki`. You should try to open the wiki first, then try `org-recipes` again.

**Comment by tuhdo** [comment]
Btw, you should be sure that the source blocks have the same major mode as the current buffer. Otherwise, the headings won't appear.

**Comment by diego-vicente** [comment]
Oh, I was messing with an org buffer to try, and the snippets were Python. Thanks!
